### ISSUE TITLE
Refactor error logs into a function

### ISSUE THREAD

**Issue by thomashockaday** [thomashockaday/misc-executables#1]
Currently, when an error outputs, this runs:

```
echo 'Please make sure you are actually inside a repo,'
echo 'Then use one of the following:'
echo '$ setup docker initial'
echo '$ setup docker'
echo '$ setup vagrant initial'
echo '$ setup vagrant'
exit
```

Which can be shortened a lot. I propose error functions for each docker and vagrant, and a generic one that will call them both. The first two lines and the exit will also have to be contained in these somewhere.

The instances of this error log in the code can then be replaced appropriately by these function calls.

The function should be defined at the top of the file for tidiness.

**Comment by jamieburnip** [comment]
https://github.com/thomashockaday/misc-executables/pull/2
